server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quan_ly_nhan_vien_chinh_phu
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded

logging:
  level:
    org:
      springframework:
        security: DEBUG

